title: Guilherme | OSINT & Cybersecurity Specialist
theme: jekyll-theme-minimal
description: Portfolio with real OSINT investigations, cybersecurity case studies, and technical skills.
logo: /assets/profile.jpg  
show_downloads: false
