title: Guilherme Leite | Cybersecurity | OSINT & Digital Investigations
theme: jekyll-theme-cayman
description: I specialize in digital investigations using OSINT (Open Source Intelligence), with experience in threat hunting, profile validation, geolocation by image, and account protection. I’m also a researcher on a private bug bounty platform and a pentest enjoyer.   
show_downloads: false
