title: Guilherme Leite | Cybersecurity | OSINT & Digital Investigations
theme: jekyll-theme-minimal
description: I specialize in digital investigations using OSINT (Open Source Intelligence), with practical experience digital investigations, profile verification, image geolocation, and account security. I’m also a researcher on a private bug bounty platform and passionate about ethical hacking and pentesting. 
show_downloads: false
